// 
// Decompiled by Procyon v0.5.30
// 

package com.facebook.drawee.components;

public enum DraweeEventTracker$Event
{
    ON_ACTIVITY_START, 
    ON_ACTIVITY_STOP, 
    ON_ATTACH_CONTROLLER, 
    ON_CLEAR_CONTROLLER, 
    ON_CLEAR_HIERARCHY, 
    ON_CLEAR_OLD_CONTROLLER, 
    ON_DATASOURCE_FAILURE, 
    ON_DATASOURCE_FAILURE_INT, 
    ON_DATASOURCE_RESULT, 
    ON_DATASOURCE_RESULT_INT, 
    ON_DATASOURCE_SUBMIT, 
    ON_DETACH_CONTROLLER, 
    ON_DRAWABLE_HIDE, 
    ON_DRAWABLE_SHOW, 
    ON_HOLDER_ATTACH, 
    ON_HOLDER_DETACH, 
    ON_INIT_CONTROLLER, 
    ON_RELEASE_CONTROLLER, 
    ON_RUN_CLEAR_CONTROLLER, 
    ON_SAME_CONTROLLER_SKIPPED, 
    ON_SCHEDULE_CLEAR_CONTROLLER, 
    ON_SET_CONTROLLER, 
    ON_SET_HIERARCHY;
}
