// 
// Decompiled by Procyon v0.5.30
// 

package com.netflix.mediaclient;

public enum StatusCode
{
    ALREADY_IN_QUEUE(10), 
    BLADERUNNER_FAILURE(-320), 
    BROWSE_AGENT_WRONG_STATE(-66), 
    BROWSE_CW_WRONG_STATE(-68), 
    BROWSE_IQ_WRONG_STATE(-67), 
    CONFIG_DOWNLOAD_FAILED(-12), 
    CONFIG_REFRESH_FAILED(-7), 
    DELETED_PROFILE(-69), 
    DL_ALL_CDN_URLS_FAILED(-133), 
    DL_BUSY_TRY_DELETE_AGAIN(-150), 
    DL_CANT_CREATE_VIEWABLE_DIRECTORY(-135), 
    DL_CANT_DELETE_DOWNLOADABLES(-138), 
    DL_CANT_DELETE_PLAYABLE_DIRECTORY(-139), 
    DL_CANT_PERSIST_MANIFEST(-136), 
    DL_CANT_PERSIST_REGISTRY(-142), 
    DL_CREATE_REQUEST_ALREADY_PENDING(-146), 
    DL_ENCODES_ARE_NOT_AVAILABLE(-148), 
    DL_ENCODES_DELETE_ON_REVOCATION(-155), 
    DL_LIMIT_CANT_DOWNLOAD_TILL_DATE(-152), 
    DL_LIMIT_TOO_MANY_DEVICES_PLAN_OPTION(-154), 
    DL_LIMIT_TOO_MANY_DOWNLOADED_DELETE_SOME(-153), 
    DL_MANIFEST_DATA_MISSING(-149), 
    DL_MANIFEST_NOT_FOUND_IN_CACHE(-141), 
    DL_MANIFEST_NO_TRACKS_TO_DOWNLOAD(-137), 
    DL_NOT_ENOUGH_FREE_SPACE(-140), 
    DL_OFFLINE_AGENT_NOT_READY(-144), 
    DL_OFFLINE_PLAYABLE_NOT_FOUND(-145), 
    DL_OFFLINE_STORAGE_NOT_AVAILABLE(-134), 
    DL_PLAY_WINDOW_RENEW_FAILED(-151), 
    DL_REGISTRY_CHECKSUM_FAILED(-132), 
    DL_TITTLE_ALREADY_DOWNLOADED(-131), 
    DL_TITTLE_ALREADY_REQUESTED_FOR_DOWNLOAD(-143), 
    DL_TOTAL_LICENSE_PER_DEVICE_LIMIT(-156), 
    DL_URL_DOWNLOAD_DISK_IO_ERROR(-130), 
    DL_USER_NOT_LOGGED_IN(-147), 
    DL_WARNING_DL_N_TIMES_BEFORE_DATE(13), 
    DRM_FAILURE_CDM(-100), 
    DRM_FAILURE_CDM_EXCEPTION(-108), 
    DRM_FAILURE_CDM_KEY_SET_EMPTY(-102), 
    DRM_FAILURE_CDM_LICENSE_EMPTY(-104), 
    DRM_FAILURE_CDM_NOT_PROVISIONED(-106), 
    DRM_FAILURE_CDM_RESOURCE_BUSY(-103), 
    DRM_FAILURE_CDM_SERVER_DENIED(-107), 
    DRM_FAILURE_FORCE_CRYPTO_FALLBACK(-105), 
    DRM_FAILURE_GOOGLE_CDM_PROVISIONG_DENIED(-101), 
    DRM_FAILURE_GOOGLE_DECLINED_PROVISIONING(-119), 
    DRM_FAILURE_MEDIADRM_DECRYPT(-113), 
    DRM_FAILURE_MEDIADRM_ENCRYPT(-114), 
    DRM_FAILURE_MEDIADRM_GET_KEY_REQUEST(-115), 
    DRM_FAILURE_MEDIADRM_KEYS_RESTORE_FAILED(-117), 
    DRM_FAILURE_MEDIADRM_PROVIDE_KEY_RESPONSE(-116), 
    DRM_FAILURE_MEDIADRM_RESET(-118), 
    DRM_FAILURE_MEDIADRM_SIGN(-111), 
    DRM_FAILURE_MEDIADRM_VERIFY(-112), 
    DRM_FAILURE_MEDIADRM_WIDEVINE_PLUGIN_CHANGED(-110), 
    FALKOR_RESPONSE_PARSE_ERROR(-80), 
    FATAL_CONFIG_DOWNLOAD_FAILED(-14), 
    FORCED_TESTING_ERROR(-8), 
    HTTP_SSL_DATE_TIME_ERROR(-121), 
    HTTP_SSL_ERROR(-120), 
    HTTP_SSL_NO_VALID_CERT(-122), 
    INIT_SERVICE_TIMEOUT(-9), 
    INSUFFICIENT_CONTENT(-71), 
    INTERNAL_ERROR(-2), 
    INT_ERR_ADVIS_VIDEO_ID_NULL(-360), 
    INT_ERR_BAD_COOKIES(-369), 
    INT_ERR_CB_NULL(-365), 
    INT_ERR_CMP(-361), 
    INT_ERR_CMP_RESP_NULL(-362), 
    INT_ERR_FALKOR_EXCEPTION(-370), 
    INT_ERR_FETCH_ERROR(-373), 
    INT_ERR_FETCH_NETWORK_ERROR(-372), 
    INT_ERR_FETCH_TIMEOUT(-371), 
    INT_ERR_MDX_INIT(-363), 
    INT_ERR_MNGR_NOT_READY(-367), 
    INT_ERR_REALM_DETAILS_NULL(-366), 
    INT_ERR_RESOURCE_URL_NULL(-364), 
    INT_ERR_SERVICE_DISCONNECTED(-368), 
    INVALID_COUNRTY(-70), 
    MAP_ERROR(-65), 
    MISSING_ID_IN_CACHE(-63), 
    MSL_FAILED_TO_CREATE_CLIENT(-1001), 
    MSL_FAILED_TO_UPDATE_USER_ID(-1002), 
    MSL_LEGACY_CRYPTO(-1003), 
    NETWORK_ERROR(-3), 
    NETWORK_ERR_FILE_NOT_FOUND(-382), 
    NETWORK_ERR_TIMEOUT(-381), 
    NETWORK_ERR_VOLLEY_ERROR(-380), 
    NON_RECOMMENDED_APP_VERSION(1), 
    NON_SUPPORTED_LOCALE(2), 
    NOT_IMPLEMENTED(-10), 
    NOT_IN_QUEUE(11), 
    NOT_VALID(12), 
    NO_CONNECTIVITY(-11), 
    NRD_ERROR(-4), 
    NRD_INVALID_SW_VERSION(-20), 
    NRD_LOGIN_ACTIONID_1(-200), 
    NRD_LOGIN_ACTIONID_10(-209), 
    NRD_LOGIN_ACTIONID_11(-210), 
    NRD_LOGIN_ACTIONID_12(-211), 
    NRD_LOGIN_ACTIONID_2(-201), 
    NRD_LOGIN_ACTIONID_3(-202), 
    NRD_LOGIN_ACTIONID_4(-203), 
    NRD_LOGIN_ACTIONID_5(-204), 
    NRD_LOGIN_ACTIONID_6(-205), 
    NRD_LOGIN_ACTIONID_7(-206), 
    NRD_LOGIN_ACTIONID_8(-207), 
    NRD_LOGIN_ACTIONID_9(-208), 
    NRD_LOGIN_ONGOING(-40), 
    NRD_REGISTRATION_EXISTS(-41), 
    NRD_REGISTRATION_INVALID_CREDENTIALS(-42), 
    OBSOLETE_APP_VERSION(-5), 
    OFFLINE_LICENSE_ERROR(-323), 
    OFFLINE_LICENSE_FETCH_NEW(-324), 
    OFFLINE_LICENSE_MAX_DEVICE_LIMIT(-321), 
    OFFLINE_LICENSE_NOT_TESTER(-322), 
    OK(0), 
    RESPONSE_PARSE_ERROR(-300), 
    SERVER_ERROR(-62), 
    SERVER_ERROR_MAP_CACHE_MISS(-64), 
    SET_FAILED(-6), 
    UNKNOWN(-1), 
    USER_NOT_AUTHORIZED(-61), 
    USER_SIGNIN_FAILURE(-57), 
    USER_SIGNIN_RETRY(-58), 
    VOIP_CONFIG_DOWNLOAD_FAILED(-15), 
    WRONG_PATH(-60);
    
    private int mValue;
    
    private StatusCode(final int mValue) {
        this.mValue = mValue;
    }
    
    public static StatusCode getStatusCodeByValue(final int n) {
        final StatusCode[] values = values();
        for (int length = values.length, i = 0; i < length; ++i) {
            final StatusCode statusCode = values[i];
            if (statusCode != null && statusCode.getValue() == n) {
                return statusCode;
            }
        }
        return null;
    }
    
    public int getValue() {
        return this.mValue;
    }
    
    public boolean isError() {
        return this.mValue < 0;
    }
    
    public boolean isSucess() {
        return this.mValue >= 0;
    }
    
    public boolean isWarning() {
        return this.mValue > 0;
    }
    
    @Override
    public String toString() {
        return "StatusCode: [ code: " + this.mValue + ", name: " + this.name() + "]";
    }
}
