// 
// Decompiled by Procyon v0.5.30
// 

package crittercism.android;

public enum eb
{
    a("DISKSPACEFREE_EXTERNAL_STORAGE_DIRECTORY_FAULT", 0), 
    b("DISKSPACETOTAL_EXTERNAL_STORAGE_DIRECTORY_FAULT", 1), 
    c("SDSPACEFREE_EXTERNAL_STORAGE_DIRECTORY_FAULT", 2), 
    d("SDSPACETOTAL_EXTERNAL_STORAGE_DIRECTORY_FAULT", 3), 
    e("GENERIC_HANDLER_DO_OPEN_CONNECTION_FAULT", 4), 
    f("STREAM_HANDLER_FACTORY_ANNUL_REFLECTION_FAULT", 5), 
    g("STREAM_HANDLER_FACTORY_CLEAR_STREAM_HANDLERS_FAULT", 6), 
    h("HASHED_DEVICE_ID_GENERATE_FROM_DROID_ID_FAULT", 7), 
    i("HASHED_DEVICE_ID_GENERATE_RANDOM_ID_FAULT", 8), 
    j("TXN_CRASH_ALL_FAULT", 9);
    
    private eb(final String s, final int n) {
    }
}
