// 
// Decompiled by Procyon v0.5.30
// 

package com.netflix.mediaclient.service.logging.perf;

public enum Sessions
{
    CONFIG_AGENT_LOADED, 
    DRM_LOADED, 
    FALKOR_AGENT_LOADED, 
    IMAGE_FETCH, 
    LAUNCH_ACTIVITY_LIFE, 
    LAUNCH_ACTIVITY_MANAGER_LOAD, 
    LOGGING_AGENT_LOADED, 
    LOG_IN, 
    LOLOMO_LOAD, 
    LOLOMO_PREFETCH, 
    LOLOMO_PREFETCH_DESERIALIZE, 
    LOLOMO_PREFETCH_SERIALIZE, 
    NETFLIX_SERVICE_LOADED, 
    NRD_CONTROLLER_LOADED, 
    ONRAMP_TTR, 
    PROFILE_GATE, 
    RESOURCE_FETCHER_LOAD, 
    SIGN_UP, 
    TDP, 
    TTI, 
    TTR, 
    USER_AGENT_LOADED;
}
