// 
// Decompiled by Procyon v0.5.30
// 

package com.google.android.gms.fitness;

import android.util.SparseArray;

public class FitnessActivities
{
    public static final int AEROBICS = 9;
    public static final String AEROBICS_STRING = "aerobics";
    public static final int BADMINTON = 10;
    public static final String BADMINTON_STRING = "badminton";
    public static final int BASEBALL = 11;
    public static final String BASEBALL_STRING = "baseball";
    public static final int BASKETBALL = 12;
    public static final String BASKETBALL_STRING = "basketball";
    public static final int BIATHLON = 13;
    public static final String BIATHLON_STRING = "biathlon";
    public static final int BIKING = 1;
    public static final int BIKING_HAND = 14;
    public static final String BIKING_HAND_STRING = "biking.hand";
    public static final int BIKING_MOUNTAIN = 15;
    public static final String BIKING_MOUNTAIN_STRING = "biking.mountain";
    public static final int BIKING_ROAD = 16;
    public static final String BIKING_ROAD_STRING = "biking.road";
    public static final int BIKING_SPINNING = 17;
    public static final String BIKING_SPINNING_STRING = "biking.spinning";
    public static final int BIKING_STATIONARY = 18;
    public static final String BIKING_STATIONARY_STRING = "biking.stationary";
    public static final String BIKING_STRING = "biking";
    public static final int BIKING_UTILITY = 19;
    public static final String BIKING_UTILITY_STRING = "biking.utility";
    public static final int BOXING = 20;
    public static final String BOXING_STRING = "boxing";
    public static final int CALISTHENICS = 21;
    public static final String CALISTHENICS_STRING = "calisthenics";
    public static final int CIRCUIT_TRAINING = 22;
    public static final String CIRCUIT_TRAINING_STRING = "circuit_training";
    public static final int CRICKET = 23;
    public static final String CRICKET_STRING = "cricket";
    public static final int CURLING = 106;
    public static final String CURLING_STRING = "curling";
    public static final int DANCING = 24;
    public static final String DANCING_STRING = "dancing";
    public static final int DIVING = 102;
    public static final String DIVING_STRING = "diving";
    public static final int ELLIPTICAL = 25;
    public static final String ELLIPTICAL_STRING = "elliptical";
    public static final int ERGOMETER = 103;
    public static final String ERGOMETER_STRING = "ergometer";
    public static final String EXITING_VEHICLE_STRING = "exiting_vehicle";
    public static final int FENCING = 26;
    public static final String FENCING_STRING = "fencing";
    public static final int FOOTBALL_AMERICAN = 27;
    public static final String FOOTBALL_AMERICAN_STRING = "football.american";
    public static final int FOOTBALL_AUSTRALIAN = 28;
    public static final String FOOTBALL_AUSTRALIAN_STRING = "football.australian";
    public static final int FOOTBALL_SOCCER = 29;
    public static final String FOOTBALL_SOCCER_STRING = "football.soccer";
    public static final int FRISBEE_DISC = 30;
    public static final String FRISBEE_DISC_STRING = "frisbee_disc";
    public static final int GARDENING = 31;
    public static final String GARDENING_STRING = "gardening";
    public static final int GOLF = 32;
    public static final String GOLF_STRING = "golf";
    public static final int GYMNASTICS = 33;
    public static final String GYMNASTICS_STRING = "gymnastics";
    public static final int HANDBALL = 34;
    public static final String HANDBALL_STRING = "handball";
    public static final int HIKING = 35;
    public static final String HIKING_STRING = "hiking";
    public static final int HOCKEY = 36;
    public static final String HOCKEY_STRING = "hockey";
    public static final int HORSEBACK_RIDING = 37;
    public static final String HORSEBACK_RIDING_STRING = "horseback_riding";
    public static final int HOUSEWORK = 38;
    public static final String HOUSEWORK_STRING = "housework";
    public static final int ICE_SKATING = 104;
    public static final String ICE_SKATING_STRING = "ice_skating";
    public static final int IN_VEHICLE = 0;
    public static final String IN_VEHICLE_STRING = "in_vehicle";
    public static final int JUMP_ROPE = 39;
    public static final String JUMP_ROPE_STRING = "jump_rope";
    public static final int KAYAKING = 40;
    public static final String KAYAKING_STRING = "kayaking";
    public static final int KETTLEBELL_TRAINING = 41;
    public static final String KETTLEBELL_TRAINING_STRING = "kettlebell_training";
    public static final int KICKBOXING = 42;
    public static final String KICKBOXING_STRING = "kickboxing";
    public static final int KICK_SCOOTER = 107;
    public static final String KICK_SCOOTER_STRING = "kick_scooter";
    public static final int KITESURFING = 43;
    public static final String KITESURFING_STRING = "kitesurfing";
    public static final int MARTIAL_ARTS = 44;
    public static final String MARTIAL_ARTS_STRING = "martial_arts";
    public static final int MEDITATION = 45;
    public static final String MEDITATION_STRING = "meditation";
    public static final int MIXED_MARTIAL_ARTS = 46;
    public static final String MIXED_MARTIAL_ARTS_STRING = "martial_arts.mixed";
    public static final int ON_FOOT = 2;
    public static final String ON_FOOT_STRING = "on_foot";
    public static final int OTHER = 108;
    public static final String OTHER_STRING = "other";
    public static final int P90X = 47;
    public static final String P90X_STRING = "p90x";
    public static final int PARAGLIDING = 48;
    public static final String PARAGLIDING_STRING = "paragliding";
    public static final int PILATES = 49;
    public static final String PILATES_STRING = "pilates";
    public static final int POLO = 50;
    public static final String POLO_STRING = "polo";
    public static final int RACQUETBALL = 51;
    public static final String RACQUETBALL_STRING = "racquetball";
    public static final int ROCK_CLIMBING = 52;
    public static final String ROCK_CLIMBING_STRING = "rock_climbing";
    public static final int ROWING = 53;
    public static final int ROWING_MACHINE = 54;
    public static final String ROWING_MACHINE_STRING = "rowing.machine";
    public static final String ROWING_STRING = "rowing";
    public static final int RUGBY = 55;
    public static final String RUGBY_STRING = "rugby";
    public static final int RUNNING = 8;
    public static final int RUNNING_JOGGING = 56;
    public static final String RUNNING_JOGGING_STRING = "running.jogging";
    public static final int RUNNING_SAND = 57;
    public static final String RUNNING_SAND_STRING = "running.sand";
    public static final String RUNNING_STRING = "running";
    public static final int RUNNING_TREADMILL = 58;
    public static final String RUNNING_TREADMILL_STRING = "running.treadmill";
    public static final int SAILING = 59;
    public static final String SAILING_STRING = "sailing";
    public static final int SCUBA_DIVING = 60;
    public static final String SCUBA_DIVING_STRING = "scuba_diving";
    public static final int SKATEBOARDING = 61;
    public static final String SKATEBOARDING_STRING = "skateboarding";
    public static final int SKATING = 62;
    public static final int SKATING_CROSS = 63;
    public static final String SKATING_CROSS_STRING = "skating.cross";
    public static final int SKATING_INDOOR = 105;
    public static final String SKATING_INDOOR_STRING = "skating.indoor";
    public static final int SKATING_INLINE = 64;
    public static final String SKATING_INLINE_STRING = "skating.inline";
    public static final String SKATING_STRING = "skating";
    public static final int SKIING = 65;
    public static final int SKIING_BACK_COUNTRY = 66;
    public static final String SKIING_BACK_COUNTRY_STRING = "skiing.back_country";
    public static final int SKIING_CROSS_COUNTRY = 67;
    public static final String SKIING_CROSS_COUNTRY_STRING = "skiing.cross_country";
    public static final int SKIING_DOWNHILL = 68;
    public static final String SKIING_DOWNHILL_STRING = "skiing.downhill";
    public static final int SKIING_KITE = 69;
    public static final String SKIING_KITE_STRING = "skiing.kite";
    public static final int SKIING_ROLLER = 70;
    public static final String SKIING_ROLLER_STRING = "skiing.roller";
    public static final String SKIING_STRING = "skiing";
    public static final int SLEDDING = 71;
    public static final String SLEDDING_STRING = "sledding";
    public static final int SLEEP = 72;
    public static final String SLEEP_STRING = "sleep";
    public static final int SNOWBOARDING = 73;
    public static final String SNOWBOARDING_STRING = "snowboarding";
    public static final int SNOWMOBILE = 74;
    public static final String SNOWMOBILE_STRING = "snowmobile";
    public static final int SNOWSHOEING = 75;
    public static final String SNOWSHOEING_STRING = "snowshoeing";
    public static final int SQUASH = 76;
    public static final String SQUASH_STRING = "squash";
    public static final int STAIR_CLIMBING = 77;
    public static final int STAIR_CLIMBING_MACHINE = 78;
    public static final String STAIR_CLIMBING_MACHINE_STRING = "stair_climbing.machine";
    public static final String STAIR_CLIMBING_STRING = "stair_climbing";
    public static final int STANDUP_PADDLEBOARDING = 79;
    public static final String STANDUP_PADDLEBOARDING_STRING = "standup_paddleboarding";
    public static final int STILL = 3;
    public static final String STILL_STRING = "still";
    public static final int STRENGTH_TRAINING = 80;
    public static final String STRENGTH_TRAINING_STRING = "strength_training";
    public static final int SURFING = 81;
    public static final String SURFING_STRING = "surfing";
    public static final int SWIMMING = 82;
    public static final int SWIMMING_OPEN_WATER = 84;
    public static final String SWIMMING_OPEN_WATER_STRING = "swimming.open_water";
    public static final int SWIMMING_POOL = 83;
    public static final String SWIMMING_POOL_STRING = "swimming.pool";
    public static final String SWIMMING_STRING = "swimming";
    private static final SparseArray<String> Sg;
    public static final int TABLE_TENNIS = 85;
    public static final String TABLE_TENNIS_STRING = "table_tennis";
    public static final int TEAM_SPORTS = 86;
    public static final String TEAM_SPORTS_STRING = "team_sports";
    public static final int TENNIS = 87;
    public static final String TENNIS_STRING = "tennis";
    public static final int TILTING = 5;
    public static final String TILTING_STRING = "tilting";
    public static final int TREADMILL = 88;
    public static final String TREADMILL_STRING = "treadmill";
    public static final int UNKNOWN = 4;
    public static final String UNKNOWN_STRING = "unknown";
    public static final int VOLLEYBALL = 89;
    public static final int VOLLEYBALL_BEACH = 90;
    public static final String VOLLEYBALL_BEACH_STRING = "volleyball.beach";
    public static final int VOLLEYBALL_INDOOR = 91;
    public static final String VOLLEYBALL_INDOOR_STRING = "volleyball.indoor";
    public static final String VOLLEYBALL_STRING = "volleyball";
    public static final int WAKEBOARDING = 92;
    public static final String WAKEBOARDING_STRING = "wakeboarding";
    public static final int WALKING = 7;
    public static final int WALKING_FITNESS = 93;
    public static final String WALKING_FITNESS_STRING = "walking.fitness";
    public static final int WALKING_NORDIC = 94;
    public static final String WALKING_NORDIC_STRING = "walking.nordic";
    public static final String WALKING_STRING = "walking";
    public static final int WALKING_TREADMILL = 95;
    public static final String WALKING_TREADMILL_STRING = "walking.treadmill";
    public static final int WATER_POLO = 96;
    public static final String WATER_POLO_STRING = "water_polo";
    public static final int WEIGHTLIFTING = 97;
    public static final String WEIGHTLIFTING_STRING = "weightlifting";
    public static final int WHEELCHAIR = 98;
    public static final String WHEELCHAIR_STRING = "wheelchair";
    public static final int WINDSURFING = 99;
    public static final String WINDSURFING_STRING = "windsurfing";
    public static final int YOGA = 100;
    public static final String YOGA_STRING = "yoga";
    public static final int ZUMBA = 101;
    public static final String ZUMBA_STRING = "zumba";
    
    static {
        (Sg = new SparseArray(109)).put(9, (Object)"aerobics");
        FitnessActivities.Sg.put(10, (Object)"badminton");
        FitnessActivities.Sg.put(11, (Object)"baseball");
        FitnessActivities.Sg.put(12, (Object)"basketball");
        FitnessActivities.Sg.put(13, (Object)"biathlon");
        FitnessActivities.Sg.put(1, (Object)"biking");
        FitnessActivities.Sg.put(14, (Object)"biking.hand");
        FitnessActivities.Sg.put(15, (Object)"biking.mountain");
        FitnessActivities.Sg.put(16, (Object)"biking.road");
        FitnessActivities.Sg.put(17, (Object)"biking.spinning");
        FitnessActivities.Sg.put(18, (Object)"biking.stationary");
        FitnessActivities.Sg.put(19, (Object)"biking.utility");
        FitnessActivities.Sg.put(20, (Object)"boxing");
        FitnessActivities.Sg.put(21, (Object)"calisthenics");
        FitnessActivities.Sg.put(22, (Object)"circuit_training");
        FitnessActivities.Sg.put(23, (Object)"cricket");
        FitnessActivities.Sg.put(106, (Object)"curling");
        FitnessActivities.Sg.put(24, (Object)"dancing");
        FitnessActivities.Sg.put(102, (Object)"diving");
        FitnessActivities.Sg.put(25, (Object)"elliptical");
        FitnessActivities.Sg.put(103, (Object)"ergometer");
        FitnessActivities.Sg.put(6, (Object)"exiting_vehicle");
        FitnessActivities.Sg.put(26, (Object)"fencing");
        FitnessActivities.Sg.put(27, (Object)"football.american");
        FitnessActivities.Sg.put(28, (Object)"football.australian");
        FitnessActivities.Sg.put(29, (Object)"football.soccer");
        FitnessActivities.Sg.put(30, (Object)"frisbee_disc");
        FitnessActivities.Sg.put(31, (Object)"gardening");
        FitnessActivities.Sg.put(32, (Object)"golf");
        FitnessActivities.Sg.put(33, (Object)"gymnastics");
        FitnessActivities.Sg.put(34, (Object)"handball");
        FitnessActivities.Sg.put(35, (Object)"hiking");
        FitnessActivities.Sg.put(36, (Object)"hockey");
        FitnessActivities.Sg.put(37, (Object)"horseback_riding");
        FitnessActivities.Sg.put(38, (Object)"housework");
        FitnessActivities.Sg.put(104, (Object)"ice_skating");
        FitnessActivities.Sg.put(0, (Object)"in_vehicle");
        FitnessActivities.Sg.put(39, (Object)"jump_rope");
        FitnessActivities.Sg.put(40, (Object)"kayaking");
        FitnessActivities.Sg.put(41, (Object)"kettlebell_training");
        FitnessActivities.Sg.put(107, (Object)"kick_scooter");
        FitnessActivities.Sg.put(42, (Object)"kickboxing");
        FitnessActivities.Sg.put(43, (Object)"kitesurfing");
        FitnessActivities.Sg.put(44, (Object)"martial_arts");
        FitnessActivities.Sg.put(45, (Object)"meditation");
        FitnessActivities.Sg.put(46, (Object)"martial_arts.mixed");
        FitnessActivities.Sg.put(2, (Object)"on_foot");
        FitnessActivities.Sg.put(108, (Object)"other");
        FitnessActivities.Sg.put(47, (Object)"p90x");
        FitnessActivities.Sg.put(48, (Object)"paragliding");
        FitnessActivities.Sg.put(49, (Object)"pilates");
        FitnessActivities.Sg.put(50, (Object)"polo");
        FitnessActivities.Sg.put(51, (Object)"racquetball");
        FitnessActivities.Sg.put(52, (Object)"rock_climbing");
        FitnessActivities.Sg.put(53, (Object)"rowing");
        FitnessActivities.Sg.put(54, (Object)"rowing.machine");
        FitnessActivities.Sg.put(55, (Object)"rugby");
        FitnessActivities.Sg.put(8, (Object)"running");
        FitnessActivities.Sg.put(56, (Object)"running.jogging");
        FitnessActivities.Sg.put(57, (Object)"running.sand");
        FitnessActivities.Sg.put(58, (Object)"running.treadmill");
        FitnessActivities.Sg.put(59, (Object)"sailing");
        FitnessActivities.Sg.put(60, (Object)"scuba_diving");
        FitnessActivities.Sg.put(61, (Object)"skateboarding");
        FitnessActivities.Sg.put(62, (Object)"skating");
        FitnessActivities.Sg.put(63, (Object)"skating.cross");
        FitnessActivities.Sg.put(105, (Object)"skating.indoor");
        FitnessActivities.Sg.put(64, (Object)"skating.inline");
        FitnessActivities.Sg.put(65, (Object)"skiing");
        FitnessActivities.Sg.put(66, (Object)"skiing.back_country");
        FitnessActivities.Sg.put(67, (Object)"skiing.cross_country");
        FitnessActivities.Sg.put(68, (Object)"skiing.downhill");
        FitnessActivities.Sg.put(69, (Object)"skiing.kite");
        FitnessActivities.Sg.put(70, (Object)"skiing.roller");
        FitnessActivities.Sg.put(71, (Object)"sledding");
        FitnessActivities.Sg.put(72, (Object)"sleep");
        FitnessActivities.Sg.put(73, (Object)"snowboarding");
        FitnessActivities.Sg.put(74, (Object)"snowmobile");
        FitnessActivities.Sg.put(75, (Object)"snowshoeing");
        FitnessActivities.Sg.put(76, (Object)"squash");
        FitnessActivities.Sg.put(77, (Object)"stair_climbing");
        FitnessActivities.Sg.put(78, (Object)"stair_climbing.machine");
        FitnessActivities.Sg.put(79, (Object)"standup_paddleboarding");
        FitnessActivities.Sg.put(3, (Object)"still");
        FitnessActivities.Sg.put(80, (Object)"strength_training");
        FitnessActivities.Sg.put(81, (Object)"surfing");
        FitnessActivities.Sg.put(82, (Object)"swimming");
        FitnessActivities.Sg.put(83, (Object)"swimming.pool");
        FitnessActivities.Sg.put(84, (Object)"swimming.open_water");
        FitnessActivities.Sg.put(85, (Object)"table_tennis");
        FitnessActivities.Sg.put(86, (Object)"team_sports");
        FitnessActivities.Sg.put(87, (Object)"tennis");
        FitnessActivities.Sg.put(5, (Object)"tilting");
        FitnessActivities.Sg.put(88, (Object)"treadmill");
        FitnessActivities.Sg.put(4, (Object)"unknown");
        FitnessActivities.Sg.put(89, (Object)"volleyball");
        FitnessActivities.Sg.put(90, (Object)"volleyball.beach");
        FitnessActivities.Sg.put(91, (Object)"volleyball.indoor");
        FitnessActivities.Sg.put(92, (Object)"wakeboarding");
        FitnessActivities.Sg.put(7, (Object)"walking");
        FitnessActivities.Sg.put(93, (Object)"walking.fitness");
        FitnessActivities.Sg.put(94, (Object)"walking.nordic");
        FitnessActivities.Sg.put(95, (Object)"walking.treadmill");
        FitnessActivities.Sg.put(96, (Object)"water_polo");
        FitnessActivities.Sg.put(97, (Object)"weightlifting");
        FitnessActivities.Sg.put(98, (Object)"wheelchair");
        FitnessActivities.Sg.put(99, (Object)"windsurfing");
        FitnessActivities.Sg.put(100, (Object)"yoga");
        FitnessActivities.Sg.put(101, (Object)"zumba");
    }
    
    public static int cw(final int n) {
        int n2 = n;
        if (n > 108) {
            n2 = 4;
        }
        return n2;
    }
    
    public static String getName(final int n) {
        final String s = (String)FitnessActivities.Sg.get(n);
        if (s == null) {
            throw new IllegalArgumentException("Unknown activity " + n);
        }
        return s;
    }
}
